title: flyingkimura
description: notes, plans, and experiments
url: "https://flyingkimura.co.uk"
baseurl: ""

markdown: kramdown
permalink: /blog/:year/:month/:slug/

collections:
  training_plans:
    output: true
    permalink: /training-plans/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: training_plans
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - docs
  - README.md
